### ISSUE TITLE
We should adopt the Semicolon less Javascript Convention

### ISSUE THREAD

**Issue by ghost** [40Digits/code-standards#6] opened 2016-04-15 18:57 UTC
After writing semicolon less js it has been wonderful, and has really visually cleaned up my code. As well, a lot of the JS community has been moving towards this. Most module bundlers now and days can adapt to this and insert semicolons whenever they are needed, as well the v8 engine has matured to the point of handling all but two instances of leaving out semicolons, but our module bundlers can handle this.

```
//ES5
var fnName = function fnName() {
  var name = 'name';
  if ( name === 'name' ) {
     console.log('this works');
     cb(name);
  }
};

var fnName = function fnName(cb) {
  var name = 'name'
  if ( name === 'name' ) {
    console.log('this works')
    cb(name)
  }
}
```

**Comment by ckhicks** [comment] 2016-04-15 19:05
Any implications for compiling down to old browsers, or will the 
compiler add them in?

**Comment by dsharris** [comment] 2016-04-15 19:11
The compiler would add them, but i STRONGLY disagree with this suggestion.

I rarely chime in on this stuff, but this one i will fight to the end.

Code standards are about putting a set of rules in place that make us better. That force us to write code in a better, cleaner, and more "standardized" way. Semicolon less code is not a good practice, and could quite likely cause issues for people.

Understanding the way the language works, and its limitations and constructs is an important thing. This would allow us to get away with writing incorrect code. There will come a day when each person has to work on a project that won't have our compiler systems in it, and understanding how to write code that works regardless of compilers is a tremendously useful thing.

**Comment by fredlawl** [comment] 2016-04-15 19:14
I think typescript uses semi-colons too. I'm fine with this being apart of the standard as long as we remember that some of us are heavy in the C-Style syntax and may slip up when it comes time for code review :)

**Comment by brandoncash** [comment] 2016-04-15 19:16
I'm personally a fan of no semicolons as well. We do need to be aware of environments that aren't as up-to-date as v8 and ensure that we wouldn't introduce issues with instances where historically a lack of semicolon would cause an error.
To my knowledge the only two instances where this is an issue is when a line begins with `(` or `[` and the engine assumes that you are chaining on to the previous statement. In the first instance this means either multiplication or attempting to call a function; in the second it'll attempt to access the previous statement as an array.
We need to at least determine whether this is picked up on by the compiler, bundler, or our currently supported browsers (IE9+ at least).
Although I see the point in David's comment above in wanting us to write proper code outside of our build environment, we are currently requiring babel to bring us ES2016 features so the same is true for a majority of those new syntactical features as well.
@fredlawl: linters would help alleviate that as you would see a notice.

**Comment by dsharris** [comment] 2016-04-15 19:29
Here is my issue, it creates a habit of writing code that is not compliment, and offers no benefit other than the code looking slightly "cleaner" ... a subjective opinion.

In all honesty, that second chunk of code, makes my skin crawl.

EDIT ... *\* Compliant

**Comment by brandoncash** [comment] 2016-04-15 19:35
Not sure what "not compliment" means, but agreed on it being only a stylistic subjective change.

The main benefit would be more developer happiness here; but obviously that is not a unanimously shared opinion. At the very least, we must acknowledge that a large chunk of JS devs are taking this turn. Airbnb chose to include it because it is safer which is something we need to be aware of as well. More here: http://stackoverflow.com/questions/7365172/semicolon-before-self-invoking-function/7365214%237365214

**Comment by ghost** [comment] 2016-04-15 19:46
I think it would be more telling if we are able to identify when and where we need semicolons and just introduce them there. But I agree, what it really comes down to is identifying those areas where it will fail, and analyze them to see if the cost benefit analysis is worth it. I do believe it makes the code cleaner, and another detail, which really is just a detail, to note is that the js community is moving towards this. I think it'd be beneficial to see some examples when it would break the engine. @ckhicks I do not think so. I think we will be fine, ultimately it comes down to the engine and whether the engine can parse the js. In our day, because of the JIT, just in time compilation, techniques and optimizations in most js engines we dont face the issue of semicolons breaking the js code.

**Comment by ckhicks** [comment] 2016-04-15 19:58
Aye. If there's any chance that the compiler wouldn't parse/add these _exactly_ to keep browser support in place, this is a no-go from day one in my opinion. I also lean a little toward @georgelaughalot's thinking because we want to train proper habits - if all JS will be written this way soon then so be it, but until that time we have to be careful.

Then again, you might be able to use the same logic for SASS vs SCSS syntax...in which case I'll hold further comments if we process JS to that level, since I love the former. :P

**Comment by chadwatson** [comment] 2016-04-15 20:36
I'd say "proper habits" are relative to the standards. In my opinion enforcing semi-colons should be the last of our concerns, and most of our efforts should instead be on removing habits that aren't currently "proper", you know?

**Comment by ckhicks** [comment] 2016-04-15 20:49
Depends on whether those habits/standards will cause things to break 
and/or if it will lead us to writing poor code elsewhere.

**Comment by dsharris** [comment] 2016-04-15 21:07
In the most simple concise terms i can muster. We are suggesting that we create a standard of writing syntactically incorrect code, and relying on a compiler to fix the thing we intentionally did wrong. I cannot think of a more profoundly wrong use of code standards. 

In a V8 console type ... 
var x = 1 + 1
+1

Then do the same with the proper syntactical termination ...
var x = 1 + 1;
+1;

The first results in 3 the second in 2 and a log of 1. The language uses semi-colons as line termination. It's intentional and by design of the language. Standards are to make us better, not enable us to trade subjectively cleaner code for syntactical accuracy.

**Comment by brandoncash** [comment] 2016-04-15 21:22
It's not syntactically incorrect; there is clear documentation regarding where it is necessary. I would say your example is just incorrect because `+1` is not what you were intending; you just want 1, and you'd want to `console.log()` that in a browser rather than rely on its return value.

**Comment by dsharris** [comment] 2016-04-15 21:33
The headline of the post is "We should adopt the Semicolon less Javascript Convention"

Again, make it a standard, to remove things from the standard of the language.

From the ECMAScript Spec

> Certain ECMAScript statements (empty statement, variable statement, expression statement, do-while statement, continue statement, break statement, return statement, and throw statement) **must** be terminated with semicolons. 

Unless you have a razor blade sticking out of your **;** key, there is no reason to do this.

**Comment by brandoncash** [comment] 2016-04-15 21:41
You're conveniently missing the latter half of that statement, which continues

> For convenience, however, such semicolons may be omitted from the source text in certain situations. These situations are described by saying that semicolons are automatically inserted into the source code token stream in those situations.

Automatic semicolon insertion is powerful and well documented. It does, however, warrant validating that we can rely on it.
That last statement is very much an exaggeration as there are many reasons why people are already doing this.

**Comment by ckhicks** [comment] 2016-04-15 21:44
I don't think that our code _standards_ should ever include or mandate not using a pattern that is foundational to the language itself. Regardless of the ability for a browser, compiler, etc. to correctly parse it, regardless of the language we're using that may support it, to introduce it into our standards would be a mistake, in my opinion. Let's keep the rules minimal and applicable to every situation, then deviate or modify our structure where permissible, but not as a standard itself.

**Comment by dsharris** [comment] 2016-04-15 21:51
Yes, that spec continues to say that they can in "**certain situations**" be omitted.

However I cannot believe that we are suggesting to tell our employees, that we are going to require that they write code that is syntactically incorrect.

Moreover its a standard that by definition cannot be enforced. 

In "**certain situations**" the browsers will understand what your trying to type, and complete the statement for you. In other situations, we are requiring that our devs write code that will break when not passed through a pre-compiler.

Im going to say this again, we are suggesting a standard that would require our devs to write
Code that is not syntactically correct.
Code that we can't hand off to another dev shop without it first being altered or compiled.
Code that cannot in all instances be processed by a browser.
Code that literally breaks the standard of the language. 

...

We are suggesting that we create a standard of writing code that breaks the standard of the language.

**Comment by brandoncash** [comment] 2016-04-15 21:58
> However I cannot believe that we are suggesting to tell our employees, that we are going to require that they write code that is syntactically incorrect.

This is simply not the case; it is syntactically correct as the documentation states.

We are using ES2015 as a standard currently, which requires us to rely on Babel for newer language constructs. To use ES2015 features, we are tied to the preprocessor until browser support catches up.

Even if our target was ES4, reliance on ASI is sound and utilized extremely effectively by companies much larger than ourselves. And as some discussion stated above, there is a large percentage of the JavaScript community that is moving this way.

It is syntactically valid and does not break the standard of the language.
We can hand it off to anyone in the same respects we could any other code.
As with all code we write, we need to target select browsers. If the ASI in a browser we support truly cannot support it then it likely is a moot issue and we should not rely on it--that is, however, not the case.

**Comment by chadwatson** [comment] 2016-04-15 21:59
We already suggest to write the vast majority of our browser code in a way that must be run through a pre-compiler before used in the browser. If we were sticking with that argument then we would need to stop doing a lot of things that have really helped us right better code.

**Comment by dsharris** [comment] 2016-04-15 22:12
@chadwatson Yes, we have compromised browser compliance before, in an effort to adopt compliance to the language spec itself. This is not helping anyone write better code. We are compromising syntactical accuracy and browser compliance, to please the aesthetic of a subset of our employees.

There will come a day when I have to look at someone who is learning JS for the first time and tell them "while the language requires the use of a semicolon in that instance, our code standards require that you omit it and rely on ASI / pre-processors to fix your mistake"

I'm not sure i will ever be ok with that.

**Comment by brettbierman** [comment] 2016-04-15 22:22
We should not be mandating this in our standards. We should not impose it on anyone. I think it would be proper to require semicolons if anything.  As far as ease of reading defining the point where code terminates is valuable. That said I think it's best left as personal preference.

**Comment by ghost** [comment] 2016-04-17 01:05
I think there are a few misleading statements above. To consider  `var x = 1 + 1` vs `var x = 1 + 1;`  as SYNTACTICALLY INCORRECT is a bit of a stretch. A language always has three elements that determine its validity its syntax, its static semantics, and its semantics. Syntax determines whether a string is legal, static semantics determine whether a string has meaning, and its semantics assign meaning to legal strings. Since the languages Spec determines that you can conveniently eliminate semicolons from all but a few case, there is no reason to state that this is syntactically incorrect. If it was syntactically incorrect  it would be an illegal string and throw an error. If one knows the rules of the language well enough, he/she can determine when a semicolon is needed then inject it where necessary. 

Now the phrase "while the language requires the use of a semicolon in that instance, " if grasping at a straw-man argument. No one is asking us to write against the spec, in fact, I'd love to write JS that only has Semicolons when they are needed. As well, as we think of this choice, the browser is irrelevant. It doesn't matter. The JS engine behind the browser is what matters. Thus, if there is an issue where the engine cannot parse this code accurately, even when semicolons are present where they are needed and only where they are need, then I would agree we should abandon this completely. 

<img width="843" alt="screen shot 2016-04-16 at 7 53 58 pm" src="https://cloud.githubusercontent.com/assets/11316277/14584471/0b3651e2-040d-11e6-8906-fcef6d60b3eb.png">

It also seems that the meaning of the spec got lost in all that quoting. As you can see from the screenshot above, the spec states that Certain ECMAScript statements must be terminated with semicolons. But the spec goes on to say, "For convenience, however, such semicolons may be omitted from the source text in certain situations." The however in that sentence necessarily ties it to the sentence the precedes it. To take one and leave the other would be to bastardize the intention of the writers of the spec. 

We keep referencing a 'standard', but it seems if we are claiming that the standard claims that semicolon less js is syntactically incorrect, then we may be reading our own standard and not the spec. The only standard on JS is the Spec. 

All that being said, to clarify, what I mean by semicolon less JS, is to only introduce them when necessary. Or adapt our build process to handle these situations. Its a point of artistry for me, to see someone introduce semicolons only when necessary and understand the language to a high extent. No one is calling to abandon the Spec, or write syntactically incorrect JS. It does not seem to me that any of the statements against semicolon less js stand when examining them. 

Bring this back into context, these are our standards if we do not like the idea, we do not have to implement. I am perfectly ok with the majority of our team saying no and us abandoning this idea completely. This doesnt HAVE to be implemented for me to be happy. If it is left as a matter of preference i'd be happy as well, but it appears that not all would be in favor and thus would cause discrepancies across our teams projects. So if we do not want to implement this, I would be happy with requiring them. It would add more consistency to our projects.

**Comment by ghost** [comment] 2016-04-17 03:23
Also, just went back and checked all browsers are compliant to the ASI, automatic semicolon insertion, at all times, which makes sense since the rules for ASI are baked into the language spec. Something to note as well is that simply putting semicolons everywhere will not save us from errors, you still have to have a good understanding of JS ASI rules. "There are five restricted productions in the grammar, they are the postfix operators ++ and --, continue statements, break statements, return statements, and throw statements."_1_ As well, ASI is not a new or up and coming feature of JS, it has been around since the early days of JS.(_These rules date back to the early days of JavaScript, in the late 90s._)_2_

As well, if we are worried about implementation, NPM.js is written using a semicolon less style, as well as request. These two packages have been using semicolon less style for a while now without a single problem. Throughout their code base you will only find semicolons where they are needed. So if there was an issue where this style would cause a failure in production, these codebases would be riddle with issues, but they are not. They are in production, and they are functioning well. 

One good point brought up by @brandoncash, was that our minifiers or bundlers, \* **to be honest im not sure what he said, so this is only valid is so much as my assumption of what he said is correct**, would break if we adopted a semicolon less js style. Upon inspecting the source code of webpack, and doing some research on the side, the contract that these minifiers and bundlers hold is that they will not break working code. Thus, when parsing a code base and generating an  AST, abstract syntax tree, these bundlers and minifers are spec compliant, which means they understand ASI. More than that, they implement it correctly down to Specification. If they fail to do so, they are non-compliant to the Spec, therefore, we should abandon it and replace it with one that is Spec compliant. But as far as I have seen and inspected, most of our tools seem to be Spec compliant. ( That's not to say that some aren't, simply to say that I have not inspected all of them. )
1. http://inimino.org/~inimino/blog/javascript_semicolons
2. http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding

**Comment by ckhicks** [comment] 2016-04-17 03:32
Nice research! :thumbsup:

Seems like we need to make sure our repos (and developers) can fully 
embrace existing spec before we do any editing to our standards, 
especially having just finished establishing it a month or two ago. We 
have more immediate concerns of creating unity around what we already 
have than making more tweaks right now.

I'm going to pause this discussion because it's something we need to 
discuss internally for the scope/direction/training of our team. Once we 
revisit it a bit we can either re-open this discussion or form an 
initiative to take a more comprehensive look at structure down the road.

**Closed as completed** 2016-04-17 03:33 UTC
